# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171001_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
